
function getCookie(cname) {
  let name = cname + "=";
  let decodedCookie = decodeURIComponent(document.cookie);
  let ca = decodedCookie.split(';');
  for(let i = 0; i <ca.length; i++) {
    let c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}

  var patterns_json = {"6236" : "Patrón Creativo", "6212" : "Patrón Resolutivo", "7513" : "Patrón Orientado a Resultados", "7712" : "Patrón Alentador", "5723" : "Patrón del Persuasivo", "3622" : "Patrón del Promoto", "2762" : "Patrón del Consejero", "2674" : "Patrón del Agente", "2364" : "Patrón del Especialista", "5275" : "Patrón del Investigador", "3267" : "Patrón del Perfeccionista", "3236" : "Patrón del Objetivo", "4726" : "Patrón del Evaluador", "2657" : "Patrón Profesional", "5363" : "Patrón del Realizador"};
  var patterns_detail = {"6236" : "Emociones: acepta la agresión; se contiene al expresarse.<br>Meta: dominio; logros únicos.<br>Juzga a los otros según: sus estándares personales; sus ideas progresistas para realizar tareas.<br>Influye a otras personas mediante: su habilidad para establecer un ritmo a seguir en el desarrollo de sistemas y enfoques innovadores.<br>Su valor para la organización: inicia o diseña cambios.<br>Abusa de: franqueza brusca; actitud crítica o condescendiente.<br>Bajo presión: se aburre con trabajos rutinarios; se enfurruña cuando se le restringe; actúa independientemente.<br>Teme: No poder influir, no poder alcanzar sus estándares.<br>Sería más efectivo al: ser más cálido; tener más tacto al comunicarse; colaborar más efectivamente con su equipo; aceptar las reglas existentes.",
"6212" : "Emociones: Centrado en satisfacer sus necesidades personales.<br>Meta: Nuevas oportunidades<br>Juzga a los otros según: su habilidad para cumplir con los estándares del Resolutivo.<br>Influye a otras personas mediante: su búsqueda de soluciones a problemas; su capacidad para proyectar una imagen de poder.<br>Su valor para la organización: evita ceder o no asumir responsabilidades; busca métodos nuevos o innovadores para resolver problemas.<br>Abusa de: control sobre la gente y las situaciones para lograr sus propios resultados.<br>Bajo presión: trabaja por si solo para completar tareas; se torna beligerante cuando se ve su individualismo amenazado o cuando pierde oportunidades desafiantes.<br>Teme: el aburrimiento; la pérdida de control.<br>Sería más efectivo al: tener más paciencia y empatía; participar y colaborar más con los demás.",
"7513" : "Emociones: verbaliza lo que quiere de manera resuelta; muestra un individualismo inquebrantable.<br>Meta: dominio e independencia.<br>Juzga a los otros según: su habilidad para efectuar tareas rápidamente.<br>Influye a otras personas mediante: su fuerza de carácter; su presencia.<br>Su valor para la organización: presencia; tenacidad.<br>Abusa de: su impaciencia; sentido competitivo concebido en términos de “si una parte gana, la otra tiene que perder”<br>Bajo presión: se torna crítico, centrado en encontrar fallas; se resiste a trabajar en equipo; puede excederse en sus prerrogativas.<br>Teme: que otros se aprovechen de él; la lentitud, particularmente en actividades del trabajo; que se les considere incauto o bonachón.<br>Sería más efectivo al: verbalizar más lógica; considerar más los puntos de vistas de otros sobre las metas y soluciones a problemas; desarrollar un interés genuino por los demás; volverse más paciente y humilde.",
"7712" : "Emociones: acepta la agresión; aparenta no tener mucha necesidad de afecto.<br>Meta: control de sus oyentes o de su ambiente.<br>Juzga a los otros según: la forma como proyectan su fuerza personal, su carácter y su poder social.<br>Influye a otras personas mediante: su encanto, orientación, intimidación; uso de recompensas.<br>Su valor para la organización: actúa como un agente que “mueve a la gente”, inicia, exige, felicita, llama al orden y sanciona.<br>Abusa de: actitud de “el fin justifica los medios”.<br>Bajo presión: se torna manipulador, pendenciero o beligerante.<br>Teme: ser demasiado blando; perder estatus social.<br>Sería más efectivo al: desarrollar más sensibilidad genuina; estar más dispuesto a ayudar a los demás a tener éxito en su propio desarrollo personal.",
"5723" : "Emociones: Confía en los demás; es entusiasta.<br>Meta: Autoridad y prestigio; símbolos de estatus.<br>Juzga a los otros según: Su capacidad de expresarse verbalmente; su flexibilidad.<br>Influye a otras personas mediante: su comportamiento amistoso, abierto, su habilidad de expresión verbal.<br>Su valor para la organización: vende y cierra tratos; delega responsabilidad; es confiado y se desenvuelve bien.<br>Abusa de: su entusiasmo; su habilidad para vender; su optimismo.<br>Bajo presión: se torna indeciso y es fácil de convencer; se vuelve organizado para generar una buena impresión.<br>Teme: ambiente incambiable; relaciones complejas.<br>Sería más efectivo al: tener más tareas que impliquen un desafío; prestar más atención a un servicio centrado en oficios y detalles claves; efectuar más análisis objetivo de datos.",
"3622" : "Emociones: Dispuesta a aceptar a los demás.<br>Meta: Obtener aprobación, popularidad.<br>Juzga a los otros según: según sus habilidades verbales.<br>Influye a otras personas mediante: Elogios, oportunidades favores.<br>Su valor para la organización: Alivia tensiones; promueve proyectos y personas, incluso a si mismo.<br>Abusa de: los elogios y el optimismo.<br>Bajo presión: se vuelve descuidado y sentimental; es desorganizado.<br>Teme: perder la aceptación social y su valía personal.<br>Sería más efectivo al: tener más control del tiempo; lograr mayor Objetividad; tener una mayor noción de lo que es urgente; lograr un mayor control sobre sus emociones; cumplir su promesas y trabajo.",
"2762" : "Emociones: Fácil de abordar; afectuoso y comprensivo.<br>Meta: amistad; felicidad.<br>Juzga a los otros según: su aceptación de otras personas; su habilidad de buscar el lado bueno de la gente.<br>Influye a otras personas mediante: relaciones personales; política de “puertas abiertas”<br>Su valor para la organización: Estable y Predecible; amplia esfera de amistades; disposición para escuchar los sentimientos de los demás.<br>Abusa de: métodos indirectos de abordar asuntos; tolerancia.<br>Bajo presión: se torna demasiado flexible e íntimo; confía demasiado en todos sin distinción.<br>Teme: presionar a las personas; ser acusado de hacer daño.<br>Sería más efectivo al: prestar más atención a fechas de entrega realistas; tener mas iniciativa para terminar tareas.",
"2674" : "Emociones: acepta el afecto; rechaza la agresión.<br>Meta: ser aceptad por el grupo.<br>Juzga a los otros según: Compromiso por tolerar e incluir a todos.<br>Influye a otras personas mediante: empatía; amistad.<br>Su valor para la organización: apoya, propone armonía, establece lazos de empatía, se centra en dar servicio.<br>Abusa de: amabilidad.<br>Bajo presión: se vuelve persuasivo, empleando información o amistades claves de ser necesario.<br>Teme: las disensiones; los conflictos.<br>Sería más efectivo al: adquirir una noción más fuerte de que es y de que es capaz de hacer; tener mas firmeza y capacidad para imponer sus argumentos; desarrollar una mayor habilidad para decir “no” cuando resulte apropiado.",
"2364" : "Emociones: Moderación calculada; afán de servir, hacer sentir a los demás cómodos y adaptarse a ellos.<br>Meta: Conservar el orden establecido; tener un ambiente controlado.<br>Juzga a los otros según: Estándares de amistad; su capacidad.<br>Influye a otras personas mediante: Su desempeño consistente; su afán de servir, hacer sentir a los demás cómodos y adaptarse a ellos.<br>Su valor para la organización: Planea a corto plazo; es predecible, consistente; mantiene el ritmo constante.<br>Abusa de: Su modestia; su renuencia a tomar riesgos; su resistencia pasiva ante la innovación.<br>Bajo presión: Se torna adaptable a quienes tienen la autoridad y piensa con el grupo.<br>Teme: Los cambios, La desorganización.<br>Sería más efectivo al: Argumentar sus ideas públicamente; aumentar su autoconfianza basándose en la retroalimentación que recibe; empleara métodos más sencillos y rápidos.",
"5275" : "Emociones: es desapasionado; Muestra autodisciplina<br>Meta: El poder mediante cargos de autoridad y roles formales.<br>Juzga a los otros según: Su uso de información objetiva.<br>Influye a otras personas mediante: Su determinación, su tenacidad.<br>Su valor para la organización: Supervisa exhaustivamente para que los trabajos sean completados; trabaja con determinación, ya sea individualmente o en grupo pequeño.<br>Abusa de: Su franqueza brusca; suspicacia de los demás.<br>Bajo presión: Tiende a interiorizar los conflictos; guarda rencores.<br>Teme: Involucrarse con las masas; ser el encargado de vender ideas abstractas.<br>Sería más efectivo al: Ser más flexible; aceptas más a los demás; involucrarse más con los demás en el ámbito personal.",
"3267" : "Emociones: Demuestra ser competente; es moderado y cauteloso.<br>Meta: Estabilidad; logras predecibles.<br>Juzga a los otros según: sus propios estándares precisos.<br>Influye a otras personas mediante: su atención al detalle; su precisión.<br>Su valor para la organización: Es concienzudo; mantiene los estándares; controla la calidad.<br>Abusa de: Procedimientos y controles “a toda prueba” para evitar fallas; dependencia excesiva de las personas, productos y procesos que le han funcionado bien en el pasado.<br>Bajo presión: Se torna diplomático, de mucho tacto.<br>Teme: los antagonismos<br>Sería más efectivo al: ser más flexible en su rol; ser más independiente e interdependiente; tener más fe en su valía personal.",
"3236" : "Emociones: Rechaza la agresión interpersonal.<br>Meta: La exactitud.<br>Juzga a los otros según: Su habilidad para pensar con lógica.<br>Influye a otras personas mediante: Su uso de datos, hechos y argumentos lógicos.<br>Su valor para la organización: Define i esclarece; obtiene, evalúa, y comprueba información<br>Abusa de: Análisis<br>Bajo presión: Se vuelve aprensivo.<br>Teme: Actos irracionales; el ridículo.<br>Sería más efectivo al: Revelar más sobre sí mismo a los demás; comentar más sus conocimientos y opiniones con la gente.",
"4726" : "Emociones: Un fuerte impulso por generar una buena impresión.<br>Meta: “ganar” con estilo.<br>Juzga a los otros según: su habilidad para iniciar actividades.<br>Influye a otras personas mediante: hacerles competir para lograr su reconocimiento.<br>Su valor para la organización: Logra metas con el equipo<br>Abusa de: Autoridad; ingenio<br>Bajo presión: se torna intranquilo, critico, impaciente.<br>Teme: “perder” o el “fracaso”; la desaprobación de los demás<br>Sería más efectivo al: incrementar su capacidad para terminar las tareas que inicia; mostrar más empatía cuando manifiesta su desaprobación; adquirir un ritmo más constante.",
"2657" : "Emociones: Quiere mantenerse a la altura de los demás, en cuanto a su esfuerzo y su desempeño técnico.<br>Meta: Desarrollo personal.<br>Juzga a los otros según: su autodisciplina; sus cargos y ascensos<br>Influye a otras personas mediante: en su confianza en su capacidad para dominar habilidades nuevas; desarrollo de procedimientos y acciones “apropiados”<br>Su valor para la organización: es hábil para resolver problemas técnicos y humanos; demuestra su carácter competente y especializado.<br>Abusa de: una atención excesiva de sus objetos personales; expectativas poco realistas de los demás.<br>Bajo presión: se vuelve moderado; es sensible a la crítica.<br>Teme: ser predecible; no ser reconocido como un “experto”.<br>Sería más efectivo al: colaborar en forma más genuina para beneficio general; delegar más tareas claves a individuos apropiados.",
"5363" : "Emociones: Es trabajador y diligente; manifiesta frustración.<br>Meta: logras personales, a veces a expensas de la meta del grupo.<br>Juzga a los otros según: su habilidad para lograr resultados concretos.<br>Influye a otras personas mediante: su responsabilidad con su propio trabajo.<br>Su valor para la organización: determina y logra resultados en áreas claves para sí mismo.<br>Abusa de: depender demasiado de sí mismo; ensimismamiento en la tarea.<br>Bajo presión: se frustra e impacienta; se convierte más en una persona que lo hace todo en vez de delegar.<br>Teme: a otros estándares de trabajo inferiores a los suyos o que compiten contra los suyos y que por esto afecten los resultados.<br>Sería más efectivo al: pensar menos en términos “esto - o lo otro”; adquirir una mayor claridad sobre las prioridades de las tareas; dar mayor consideración a los enfoques opcionales; estar más dispuesto a transar beneficios a corto plazos a favor de aquellos a largo plazo"};